// Code generated by @Rest annotation processor. DO NOT EDIT.
package handlers

import (
	"net/http"
)

func (s *Container) Handlers() map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		http.MethodGet:    s.getContainer,
		http.MethodPatch:  s.patchContainer,
		http.MethodDelete: s.deleteContainer,
	}
}

func (s *Container) Path() string {
	return "/api/v1/containers/{container_id}"
}

func (s *Containers) Handlers() map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		http.MethodGet: s.getContainers,
	}
}

func (s *Containers) Path() string {
	return "/api/v1/containers"
}

func (s *Service) Handlers() map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		http.MethodGet:    s.getService,
		http.MethodPatch:  s.patchService,
		http.MethodDelete: s.deleteService,
	}
}

func (s *Service) Path() string {
	return "/api/v1/services/{service_id}"
}

func (s *Services) Handlers() map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		http.MethodGet: s.getServices,
	}
}

func (s *Services) Path() string {
	return "/api/v1/services"
}
